apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: json-log-http
spec:
  configPatches:
  - applyTo: HTTP_ROUTE
    match:
      context: ANY
    patch:
      operation: MERGE
      value:
        route:
          typed_per_filter_config:
            envoy.filters.http.router:
              "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
              access_log:
              - name: envoy.access_loggers.file
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.file.v3.FileAccessLog
                  path: /dev/stdout
                  json_format:
                    protocol: '%PROTOCOL%'
                    duration: '%DURATION%'
                    start_time: '%START_TIME%'
                    method: '%REQ(:METHOD)%'
                    path: '%REQ(X-ENVOY-ORIGINAL-PATH?:PATH)%'
                    response_code: '%RESPONSE_CODE%'
                    response_flags: '%RESPONSE_FLAGS%'
                    bytes_received: '%BYTES_RECEIVED%'
                    bytes_sent: '%BYTES_SENT%'
                    upstream_host: '%UPSTREAM_HOST%'
                    upstream_cluster: '%UPSTREAM_CLUSTER%'
                    downstream_remote_address: '%DOWNSTREAM_REMOTE_ADDRESS%'
                    user_agent: '%REQ(USER-AGENT)%'